import EverettianDecoherence.Approximation.StabilitySharpness.DiffuseFamilyModes
import Mathlib.Analysis.InnerProductSpace.Projection.Reflection
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic

/-!
**FR.** Réalisation unitaire de la rotation diffuse.  On construit la
rotation du plan engendré par les deux modes uniformes comme produit de deux
réflexions de droites.  L'isométrie obtenue agit par la rotation réelle
d'angle theta sur les deux modes et comme l'identité sur leur complément
orthogonal.

**EN.** Unitary realization of the diffuse rotation.  The rotation of the
plane generated by the two uniform modes is constructed as a product of two
line reflections.  The resulting linear isometry acts by the real
angle-theta rotation on the two modes and as the identity on their common
orthogonal complement.
-/

namespace EverettianDecoherence.Approximation

open QuantumFoundations.BornRule Gleason
open EverettianProbability.Abstract
open Filter
open scoped Classical InnerProductSpace BigOperators

noncomputable section

noncomputable def diffuseMidMode (m : ℕ) (θ : ℝ) : H (m + m) :=
  ((Real.cos (θ / 2) : ℝ) : ℂ) • diffuseLeftMode m +
    ((Real.sin (θ / 2) : ℝ) : ℂ) • diffuseRightMode m

theorem diffuseMidMode_inner_left
    {m : ℕ} (hm : 0 < m) (θ : ℝ) :
    inner ℂ (diffuseMidMode m θ) (diffuseLeftMode m) =
      (Real.cos (θ / 2) : ℂ) := by
  have hstar :
      star ((Real.cos (θ / 2) : ℂ)) = (Real.cos (θ / 2) : ℂ) := by
    simp
  simp [diffuseMidMode, inner_smul_left,
    diffuseLeftMode_norm hm, inner_self_eq_norm_sq_to_K,
    diffuseRightMode_inner_leftMode hm, hstar]

theorem diffuseMidMode_inner_right
    {m : ℕ} (hm : 0 < m) (θ : ℝ) :
    inner ℂ (diffuseMidMode m θ) (diffuseRightMode m) =
      (Real.sin (θ / 2) : ℂ) := by
  have hstar :
      star ((Real.sin (θ / 2) : ℂ)) = (Real.sin (θ / 2) : ℂ) := by
    simp
  simp [diffuseMidMode, inner_smul_left,
    diffuseRightMode_norm hm, inner_self_eq_norm_sq_to_K,
    diffuseLeftMode_inner_rightMode hm,
    diffuseRightMode_inner_leftMode hm, hstar]

theorem diffuseMidMode_norm
    {m : ℕ} (hm : 0 < m) (θ : ℝ) :
    ‖diffuseMidMode m θ‖ = 1 := by
  have hcosstar :
      star ((Real.cos (θ / 2) : ℂ)) = (Real.cos (θ / 2) : ℂ) := by
    simp
  have hsinstar :
      star ((Real.sin (θ / 2) : ℂ)) = (Real.sin (θ / 2) : ℂ) := by
    simp
  have hsq : ‖diffuseMidMode m θ‖ ^ 2 = 1 := by
    rw [@norm_sq_eq_re_inner ℂ]
    change (inner ℂ (diffuseMidMode m θ) (diffuseMidMode m θ)).re = 1
    simp [diffuseMidMode, inner_add_right,
      inner_smul_left, inner_smul_right,
      diffuseLeftMode_norm hm, diffuseRightMode_norm hm,
      inner_self_eq_norm_sq_to_K,
      diffuseLeftMode_inner_rightMode hm,
      diffuseRightMode_inner_leftMode hm,
      hcosstar, hsinstar, Real.sin_sq_add_cos_sq]
  nlinarith [norm_nonneg (diffuseMidMode m θ)]

/-- Product of the reflection in the left mode with the reflection in the
half-angle mode.  Composition order is chosen so that the left mode is sent
to cos(theta) a + sin(theta) b. -/
noncomputable def diffuseRotation (m : ℕ) (θ : ℝ) :
    H (m + m) ≃ₗᵢ[ℂ] H (m + m) :=
  (ℂ ∙ diffuseLeftMode m).reflection.trans
    (ℂ ∙ diffuseMidMode m θ).reflection

private theorem diffuseLeft_reflection_self
    {m : ℕ} (hm : 0 < m) :
    (ℂ ∙ diffuseLeftMode m).reflection (diffuseLeftMode m) =
      diffuseLeftMode m := by
  rw [Submodule.reflection_singleton_apply]
  rw [inner_self_eq_norm_sq_to_K, diffuseLeftMode_norm hm]
  norm_num
  module

private theorem diffuseLeft_reflection_right
    {m : ℕ} (hm : 0 < m) :
    (ℂ ∙ diffuseLeftMode m).reflection (diffuseRightMode m) =
      - diffuseRightMode m := by
  rw [Submodule.reflection_singleton_apply,
    diffuseLeftMode_inner_rightMode hm]
  simp [diffuseLeftMode_norm hm]

theorem diffuseRotation_apply_left_half
    {m : ℕ} (hm : 0 < m) (θ : ℝ) :
    diffuseRotation m θ (diffuseLeftMode m) =
      (((2 * Real.cos (θ / 2) ^ 2 - 1 : ℝ) : ℂ) •
          diffuseLeftMode m) +
        (((2 * Real.sin (θ / 2) * Real.cos (θ / 2) : ℝ) : ℂ) •
          diffuseRightMode m) := by
  unfold diffuseRotation
  rw [LinearIsometryEquiv.trans_apply, diffuseLeft_reflection_self hm,
    Submodule.reflection_singleton_apply,
    diffuseMidMode_inner_left hm θ, diffuseMidMode_norm hm θ]
  simp [diffuseMidMode]

theorem diffuseRotation_apply_right_half
    {m : ℕ} (hm : 0 < m) (θ : ℝ) :
    diffuseRotation m θ (diffuseRightMode m) =
      (((-2 * Real.sin (θ / 2) * Real.cos (θ / 2) : ℝ) : ℂ) •
          diffuseLeftMode m) +
        ((((1 - 2 * Real.sin (θ / 2) ^ 2) : ℝ) : ℂ) •
          diffuseRightMode m) := by
  unfold diffuseRotation
  rw [LinearIsometryEquiv.trans_apply, diffuseLeft_reflection_right hm,
    Submodule.reflection_singleton_apply]
  have hinner :
      inner ℂ (diffuseMidMode m θ) (- diffuseRightMode m) =
        (- Real.sin (θ / 2) : ℂ) := by
    rw [inner_neg_right, diffuseMidMode_inner_right hm θ]
    simp
  rw [hinner, diffuseMidMode_norm hm θ]
  simp [diffuseMidMode]
  module

theorem diffuseRotation_apply_left
    {m : ℕ} (hm : 0 < m) (θ : ℝ) :
    diffuseRotation m θ (diffuseLeftMode m) =
      ((Real.cos θ : ℝ) : ℂ) • diffuseLeftMode m +
        ((Real.sin θ : ℝ) : ℂ) • diffuseRightMode m := by
  rw [diffuseRotation_apply_left_half hm θ]
  have hcos :
      Real.cos θ = 2 * Real.cos (θ / 2) ^ 2 - 1 := by
    calc
      Real.cos θ = Real.cos (2 * (θ / 2)) := by congr 1 <;> ring
      _ = 2 * Real.cos (θ / 2) ^ 2 - 1 := Real.cos_two_mul _
  have hsin :
      Real.sin θ = 2 * Real.sin (θ / 2) * Real.cos (θ / 2) := by
    calc
      Real.sin θ = Real.sin (2 * (θ / 2)) := by congr 1 <;> ring
      _ = 2 * Real.sin (θ / 2) * Real.cos (θ / 2) := Real.sin_two_mul _
  rw [hcos, hsin]

theorem diffuseRotation_apply_right
    {m : ℕ} (hm : 0 < m) (θ : ℝ) :
    diffuseRotation m θ (diffuseRightMode m) =
      - ((Real.sin θ : ℝ) : ℂ) • diffuseLeftMode m +
        ((Real.cos θ : ℝ) : ℂ) • diffuseRightMode m := by
  rw [diffuseRotation_apply_right_half hm θ]
  have hsin :
      Real.sin θ = 2 * Real.sin (θ / 2) * Real.cos (θ / 2) := by
    calc
      Real.sin θ = Real.sin (2 * (θ / 2)) := by congr 1 <;> ring
      _ = 2 * Real.sin (θ / 2) * Real.cos (θ / 2) := Real.sin_two_mul _
  have hcos0 :
      Real.cos θ = 2 * Real.cos (θ / 2) ^ 2 - 1 := by
    calc
      Real.cos θ = Real.cos (2 * (θ / 2)) := by congr 1 <;> ring
      _ = 2 * Real.cos (θ / 2) ^ 2 - 1 := Real.cos_two_mul _
  have htrig := Real.sin_sq_add_cos_sq (θ / 2)
  have hcos :
      Real.cos θ = 1 - 2 * Real.sin (θ / 2) ^ 2 := by
    rw [hcos0]
    nlinarith
  rw [hsin, hcos]
  have hneg :
      (((-2 * Real.sin (θ / 2) * Real.cos (θ / 2) : ℝ) : ℂ)) =
        - (((2 * Real.sin (θ / 2) * Real.cos (θ / 2) : ℝ) : ℂ)) := by
    push_cast
    ring
  rw [hneg]
  simp only [neg_smul]

theorem diffuseRotation_apply_of_orthogonal
    {m : ℕ} (hm : 0 < m) (θ : ℝ) (x : H (m + m))
    (ha : inner ℂ (diffuseLeftMode m) x = 0)
    (hb : inner ℂ (diffuseRightMode m) x = 0) :
    diffuseRotation m θ x = x := by
  have hw : inner ℂ (diffuseMidMode m θ) x = 0 := by
    simp [diffuseMidMode, inner_smul_left, ha, hb]
  have hrefLeft :
      (ℂ ∙ diffuseLeftMode m).reflection x = -x := by
    rw [Submodule.reflection_singleton_apply, ha]
    simp [diffuseLeftMode_norm hm]
  have hwn :
      inner ℂ (diffuseMidMode m θ) (-x) = 0 := by
    rw [inner_neg_right, hw]
    simp
  have hrefMid :
      (ℂ ∙ diffuseMidMode m θ).reflection (-x) = x := by
    rw [Submodule.reflection_singleton_apply, hwn]
    simp [diffuseMidMode_norm hm θ]
  unfold diffuseRotation
  rw [LinearIsometryEquiv.trans_apply, hrefLeft, hrefMid]

end
end EverettianDecoherence.Approximation
