import EverettianDecoherence.Approximation.ExactTwoCellRigidityConverse
import EverettianDecoherence.Approximation.UnitaryInverseSymmetry
import Mathlib.Analysis.InnerProductSpace.LinearMap

/-!
**FR.** Géométrie rang-un des cellules. Pour une cellule engendrée par un
vecteur unitaire e, le bloc sortant P^\perp U P est un opérateur de rang un.
Sa norme s'obtient donc exactement via le lemme de norme des opérateurs
rang-un de Mathlib.

**EN.** Rank-one cell geometry. For a cell generated by a unit vector e, the
outgoing block P^\perp U P is rank one. Its norm is therefore obtained exactly
from Mathlib's rank-one norm lemma.
-/

namespace EverettianDecoherence.Approximation

open QuantumFoundations.BornRule Gleason
open EverettianProbability.Abstract
open EverettianDecoherence.Metrics
open scoped Classical InnerProductSpace

noncomputable section

/-- The aggregate projector of a singleton cell is the cell projector itself. -/
theorem recordSubsetProjector_singleton
    {n : ℕ} (D : Perspective n)
    (c : (Projective.interface n).Cell D) :
    Gleason.projL (recordSubsetSubspace D {c}) =
      Gleason.projL c.val := by
  rw [recordSubsetProjector_eq_sum]
  simp

/-- On a rank-one cell c = span{e}, the outgoing cross block is the rank-one
operator generated by the orthogonal component of Ue and by e. -/
theorem recordSubsetOutgoingCLM_singleton_eq_rankOne
    {n : ℕ} (D : Perspective n)
    (U : H n ≃ₗᵢ[ℂ] H n)
    (c : (Projective.interface n).Cell D)
    (e : H n) (he : ‖e‖ = 1)
    (hc : c.val = ℂ ∙ e) :
    recordSubsetOutgoingCLM D U {c} =
      InnerProductSpace.rankOne ℂ
        (U e - Gleason.projL c.val (U e)) e := by
  apply ContinuousLinearMap.ext
  intro x
  rw [recordSubsetOutgoingCLM_apply]
  unfold recordSubsetOutgoing
  rw [recordSubsetProjector_compl_apply_eq_sub D {c}
    (U (Gleason.projL (recordSubsetSubspace D {c}) x))]
  rw [recordSubsetProjector_singleton D c]
  rw [hc]
  change
    U ((ℂ ∙ e).starProjection x) -
        (ℂ ∙ e).starProjection (U ((ℂ ∙ e).starProjection x)) =
      InnerProductSpace.rankOne ℂ
        (U e - (ℂ ∙ e).starProjection (U e)) e x
  rw [Submodule.starProjection_unit_singleton ℂ he]
  rw [InnerProductSpace.rankOne_apply]
  simp only [map_smul]
  module

/-- Exact outgoing-block norm on a unit rank-one cell. -/
theorem recordSubsetOutgoingCLM_singleton_opNorm
    {n : ℕ} (D : Perspective n)
    (U : H n ≃ₗᵢ[ℂ] H n)
    (c : (Projective.interface n).Cell D)
    (e : H n) (he : ‖e‖ = 1)
    (hc : c.val = ℂ ∙ e) :
    ‖recordSubsetOutgoingCLM D U {c}‖ =
      ‖U e - Gleason.projL c.val (U e)‖ := by
  rw [recordSubsetOutgoingCLM_singleton_eq_rankOne D U c e he hc,
    InnerProductSpace.norm_rankOne, he, mul_one]

/-- Pythagorean formula for the outgoing component of a unit vector under a
unitary. -/
theorem outgoing_rankOne_norm_sq
    {n : ℕ}
    (U : H n ≃ₗᵢ[ℂ] H n)
    (c : Submodule ℂ (H n))
    (e : H n) (he : ‖e‖ = 1) :
    ‖U e - Gleason.projL c (U e)‖ ^ 2 =
      1 - ‖Gleason.projL c (U e)‖ ^ 2 := by
  have hpyth :=
    c.norm_sq_eq_add_norm_sq_starProjection (U e)
  have horth :
      cᗮ.starProjection (U e) =
        U e - c.starProjection (U e) :=
    Submodule.starProjection_orthogonal_val (K := c) (U e)
  rw [horth] at hpyth
  change
    ‖U e - Gleason.projL c (U e)‖ ^ 2 =
      1 - ‖Gleason.projL c (U e)‖ ^ 2
  have hUnorm : ‖U e‖ = 1 := by
    rw [U.norm_map, he]
  rw [hUnorm] at hpyth
  have hpyth' :
      1 =
        ‖Gleason.projL c (U e)‖ ^ 2 +
          ‖U e - Gleason.projL c (U e)‖ ^ 2 := by
    change
      1 =
        ‖c.starProjection (U e)‖ ^ 2 +
          ‖U e - c.starProjection (U e)‖ ^ 2
    simpa using hpyth
  linarith

/-- The squared outgoing block norm of a rank-one cell is one minus the
squared projected diagonal amplitude. -/
theorem recordSubsetOutgoingCLM_singleton_opNorm_sq
    {n : ℕ} (D : Perspective n)
    (U : H n ≃ₗᵢ[ℂ] H n)
    (c : (Projective.interface n).Cell D)
    (e : H n) (he : ‖e‖ = 1)
    (hc : c.val = ℂ ∙ e) :
    ‖recordSubsetOutgoingCLM D U {c}‖ ^ 2 =
      1 - ‖Gleason.projL c.val (U e)‖ ^ 2 := by
  rw [recordSubsetOutgoingCLM_singleton_opNorm D U c e he hc]
  exact outgoing_rankOne_norm_sq U c.val e he

end
end EverettianDecoherence.Approximation
